import 'package:flutter/material.dart';

import '../../ui/token/pos_colors.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AndroidSmall136(),
        ]),
      ),
    );
  }
}

class AndroidSmall136 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF2A2A2A)),
          child: Stack(
            children: [
              Positioned(
                left: 16,
                top: 16,
                child: Container(
                  width: 328,
                  height: 62,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 288,
                        top: 2,
                        child: Container(
                          width: 40,
                          height: 42,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/40x42"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 162,
                        top: 0,
                        child: Container(
                          width: 118,
                          height: 45,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 10,
                                top: 0,
                                child: Text(
                                  'دکتر مریم محمودی',
                                  textAlign: TextAlign.right,
                                  style: TextStyle(
                                    color: Color(0xFFD9DBE0),
                                    fontSize: 14,
                                    fontFamily: 'IRANYekanXVF',
                                    fontWeight: FontWeight.w500,
                                    height: 1.43,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 25,
                                child: Text(
                                  'متخصص زنان زایمان',
                                  textAlign: TextAlign.right,
                                  style: TextStyle(
                                    color: Color(0xFFD9DBE0),
                                    fontSize: 14,
                                    fontFamily: 'IRANYekanXVF',
                                    fontWeight: FontWeight.w500,
                                    height: 1.43,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 11,
                        child: Container(
                          width: 24,
                          height: 24,
                          child: Stack(children: []),
                        ),
                      ),
                      Positioned(
                        left: 328,
                        top: 62,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                          child: Container(
                            width: 328,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 0.50,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                  color: Color(0xFF505050),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 385,
                child: Container(
                  width: 150,
                  height: 155,
                  decoration: ShapeDecoration(
                    color: Color(0x14159F12),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 0.50, color: Color(0xE5388E3C)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 190,
                top: 385,
                child: Container(
                  width: 150,
                  height: 155,
                  decoration: ShapeDecoration(
                    color: Color(0x14F57C00),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 0.50, color: Color(0xFFF57C00)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 556,
                child: Container(
                  width: 327.15,
                  height: 104,
                  decoration: ShapeDecoration(
                    color: Color(0x14F57C00),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 0.50, color: Color(0xFFF57C00)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 52,
                top: 282,
                child: Text(
                  'تست ورزش',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: PosColors.darkShadeRed,
                    fontSize: 16,
                    fontFamily: 'IRANYekanXVF',
                    fontWeight: FontWeight.w600,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 230,
                top: 282,
                child: Text(
                  'سونوگرافی',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF2962FF),
                    fontSize: 16,
                    fontFamily: 'IRANYekanXVF',
                    fontWeight: FontWeight.w600,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 238,
                top: 451,
                child: Text(
                  'تزریقات',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFFF57C00),
                    fontSize: 16,
                    fontFamily: 'IRANYekanXVF',
                    fontWeight: FontWeight.w600,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 137,
                top: 568,
                child: Container(
                  width: 82,
                  height: 80,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 56,
                        child: Text(
                          'سایر خدمات',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFF57C00),
                            fontSize: 16,
                            fontFamily: 'IRANYekanXVF',
                            fontWeight: FontWeight.w600,
                            height: 1.50,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17,
                        top: 0,
                        child: Container(
                          width: 48,
                          height: 48,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 48,
                                  height: 48,
                                  child: Stack(children: []),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 49,
                top: 451,
                child: Text(
                  'آزمایش خون',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xE5388E3C),
                    fontSize: 16,
                    fontFamily: 'IRANYekanXVF',
                    fontWeight: FontWeight.w600,
                    height: 1.50,
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 99,
                child: Container(
                  width: 324,
                  height: 104,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 324,
                          height: 104,
                          decoration: ShapeDecoration(
                            color: Color(0x14159F12),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 0.50, color: Color(0xFF00C853)),
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 114,
                        top: 12,
                        child: Container(
                          width: 96,
                          height: 80,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 24,
                                top: 0,
                                child: Container(
                                  width: 48,
                                  height: 48,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 48,
                                          height: 48,
                                          child: Stack(children: []),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 56,
                                child: Text(
                                  'پرداخت ویزیت',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Color(0xFF00C853),
                                    fontSize: 16,
                                    fontFamily: 'IRANYekanXVF',
                                    fontWeight: FontWeight.w600,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}