import 'package:flutter/material.dart';

import '../../ui/token/pos_colors.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          MainPageOtherServicesSearchResults(),
        ]),
      ),
    );
  }
}

class MainPageOtherServicesSearchResults extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF2A2A2A)),
          child: Stack(
            children: [
              Positioned(
                left: 16,
                top: 16,
                child: Container(
                  width: 328,
                  height: 62,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 288,
                        top: 2,
                        child: Container(
                          width: 40,
                          height: 42,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/40x42"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 162,
                        top: 0,
                        child: Container(
                          width: 118,
                          height: 45,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 10,
                                top: 0,
                                child: Text(
                                  'دکتر مریم محمودی',
                                  textAlign: TextAlign.right,
                                  style: TextStyle(
                                    color: Color(0xFFD9DBE0),
                                    fontSize: 14,
                                    fontFamily: 'IRANYekanXVF',
                                    fontWeight: FontWeight.w500,
                                    height: 1.43,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 25,
                                child: Text(
                                  'متخصص زنان زایمان',
                                  textAlign: TextAlign.right,
                                  style: TextStyle(
                                    color: Color(0xFFD9DBE0),
                                    fontSize: 14,
                                    fontFamily: 'IRANYekanXVF',
                                    fontWeight: FontWeight.w500,
                                    height: 1.43,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 11,
                        child: Container(
                          width: 24,
                          height: 24,
                          child: Stack(children: []),
                        ),
                      ),
                      Positioned(
                        left: 328,
                        top: 62,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                          child: Container(
                            width: 328,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 0.50,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                  color: Color(0xFF505050),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 102,
                child: Container(
                  height: 72,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: [
                      SizedBox(
                        width: 328,
                        child: Text(
                          'پرداخت',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: Color(0xFFE3E5E9),
                            fontSize: 16,
                            fontFamily: 'IRANYekanXVF',
                            fontWeight: FontWeight.w600,
                            height: 1.50,
                          ),
                        ),
                      ),
                      const SizedBox(height: 8),
                      SizedBox(
                        width: 328,
                        child: Text(
                          'لیست خدمات انتخاب شده به شرح زیر است. لطفا در صورت تایید گزینه پرداخت را اتخاب کنید.',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: Color(0xFFC3C5CA),
                            fontSize: 14,
                            fontFamily: 'IRANYekanXVF',
                            fontWeight: FontWeight.w500,
                            height: 1.43,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 214,
                top: 310,
                child: SizedBox(
                  width: 328,
                  child: Text(
                    'اطلاعات مراجعه کننده',
                    textAlign: TextAlign.right,
                    style: TextStyle(
                      color: Color(0xFFD9DBE0),
                      fontSize: 14,
                      fontFamily: 'IRANYekanXVF',
                      fontWeight: FontWeight.w500,
                      height: 1.43,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 250,
                child: SizedBox(
                  width: 328,
                  child: Text(
                    'لیست خدمات انتخاب شده',
                    textAlign: TextAlign.right,
                    style: TextStyle(
                      color: Color(0xFFD9DBE0),
                      fontSize: 14,
                      fontFamily: 'IRANYekanXVF',
                      fontWeight: FontWeight.w500,
                      height: 1.43,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 282,
                child: Container(
                  width: 328,
                  height: 88,
                  decoration: ShapeDecoration(
                    color: Color(0xFF2A2A2A),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 0.50, color: Color(0xFF727272)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 5,
                        offset: Offset(0, 3),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 294,
                child: Text(
                  '262,500',
                  style: TextStyle(
                    color: Color(0xFFE3E5E9),
                    fontSize: 14,
                    fontFamily: 'IRANYekanXVF',
                    fontWeight: FontWeight.w600,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 268,
                top: 294,
                child: Text(
                  'سونوگرافی',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: Color(0xFFD9DBE0),
                    fontSize: 14,
                    fontFamily: 'IRANYekanXVF',
                    fontWeight: FontWeight.w500,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 338,
                child: Text(
                  '156,800',
                  style: TextStyle(
                    color: Color(0xFFE3E5E9),
                    fontSize: 14,
                    fontFamily: 'IRANYekanXVF',
                    fontWeight: FontWeight.w600,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 281,
                top: 338,
                child: Text(
                  'تزریقات',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: Color(0xFFD9DBE0),
                    fontSize: 14,
                    fontFamily: 'IRANYekanXVF',
                    fontWeight: FontWeight.w500,
                    height: 1.43,
                  ),
                ),
              ),
              Positioned(
                left: 328,
                top: 326,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                  child: Container(
                    width: 296,
                    decoration: ShapeDecoration(
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 0.50,
                          strokeAlign: BorderSide.strokeAlignCenter,
                          color: Color(0xFF727272),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 720,
                child: Container(
                  width: 360,
                  height: 80,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 360,
                          height: 80,
                          decoration: BoxDecoration(
                            color: Color(0xFF2A2A2A),
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x0F000000),
                                blurRadius: 20,
                                offset: Offset(0, -3),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 328,
                          height: 40,
                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                          decoration: ShapeDecoration(
                            color: Color(0xFF00C853),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Text(
                                'پرداخت',
                                style: TextStyle(
                                  color: Color(0xFF2A2A2A),
                                  fontSize: 14,
                                  fontFamily: 'IRANYekanXVF',
                                  fontWeight: FontWeight.w600,
                                  height: 1.43,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}