import 'package:flutter/material.dart';

import '../../ui/token/pos_colors.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          LogInInformation(),
        ]),
      ),
    );
  }
}

class LogInInformation extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 192,
                  decoration: BoxDecoration(color: Color(0xFFF44336)),
                ),
              ),
              Positioned(
                left: 0,
                top: 112,
                child: Container(
                  width: 360,
                  height: 688,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(16),
                        topRight: Radius.circular(16),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 130,
                top: 32,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.end,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'آویهنگ',
                        textAlign: TextAlign.right,
                        style: TextStyle(
                          color: Color(0xFFE3E5E9),
                          fontSize: 20,
                          fontFamily: 'IRANYekanXVF',
                          fontWeight: FontWeight.w700,
                          height: 1.20,
                        ),
                      ),
                      const SizedBox(width: 8),
                      Container(
                        width: 29,
                        height: 32,
                        child: Stack(children: []),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 244,
                child: Container(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.end,
                          children: [
                            SizedBox(
                              width: 328,
                              child: Text(
                                'نام کاربری',
                                textAlign: TextAlign.right,
                                style: TextStyle(
                                  color: Color(0xFF61656D),
                                  fontSize: 14,
                                  fontFamily: 'IRANYekanXVF',
                                  fontWeight: FontWeight.w500,
                                  height: 1.43,
                                ),
                              ),
                            ),
                            const SizedBox(height: 12),
                            Container(
                              width: 328,
                              height: 48,
                              decoration: ShapeDecoration(
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(width: 0.50, color: Color(0xFFD9D9D9)),
                                  borderRadius: BorderRadius.circular(8),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 16),
                      Container(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.end,
                          children: [
                            SizedBox(
                              width: 328,
                              child: Text(
                                'رمز عبور',
                                textAlign: TextAlign.right,
                                style: TextStyle(
                                  color: Color(0xFF61656D),
                                  fontSize: 14,
                                  fontFamily: 'IRANYekanXVF',
                                  fontWeight: FontWeight.w500,
                                  height: 1.43,
                                ),
                              ),
                            ),
                            const SizedBox(height: 12),
                            Container(
                              width: 328,
                              height: 48,
                              decoration: ShapeDecoration(
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                  side: BorderSide(width: 0.50, color: Color(0xFFD9D9D9)),
                                  borderRadius: BorderRadius.circular(8),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 290,
                child: SizedBox(
                  width: 308,
                  child: Text(
                    '2530252614',
                    style: TextStyle(
                      color: Color(0xFF61656D),
                      fontSize: 14,
                      fontFamily: 'IRANYekanXVF',
                      fontWeight: FontWeight.w600,
                      height: 1.43,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 144,
                child: Container(
                  height: 52,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: [
                      SizedBox(
                        width: 328,
                        child: Text(
                          'ورود',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: Color(0xFF414448),
                            fontSize: 16,
                            fontFamily: 'IRANYekanXVF',
                            fontWeight: FontWeight.w600,
                            height: 1.50,
                          ),
                        ),
                      ),
                      const SizedBox(height: 8),
                      SizedBox(
                        width: 328,
                        child: Text(
                          'نام کاربری و رمز عبور خود را وارد کنید. ',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: Color(0xFF9298A3),
                            fontSize: 14,
                            fontFamily: 'IRANYekanXVF',
                            fontWeight: FontWeight.w500,
                            height: 1.43,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 684,
                child: Container(
                  width: 328,
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                  decoration: ShapeDecoration(
                    color: Color(0xFFF44336),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'احراز هویت',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 14,
                          fontFamily: 'IRANYekanXVF',
                          fontWeight: FontWeight.w600,
                          height: 1.43,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 736,
                child: Container(
                  width: 328,
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 0.50, color: Color(0xFFF44336)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        'فاقد اطلاعات نسخه الکترونیک',
                        style: TextStyle(
                          color: Color(0xFFF44336),
                          fontSize: 14,
                          fontFamily: 'IRANYekanXVF',
                          fontWeight: FontWeight.w600,
                          height: 1.43,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 392,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 8,
                        height: 8,
                        decoration: ShapeDecoration(
                          color: Color(0xFF61656D),
                          shape: OvalBorder(),
                        ),
                      ),
                      const SizedBox(width: 2),
                      Container(
                        width: 8,
                        height: 8,
                        decoration: ShapeDecoration(
                          color: Color(0xFF61656D),
                          shape: OvalBorder(),
                        ),
                      ),
                      const SizedBox(width: 2),
                      Container(
                        width: 8,
                        height: 8,
                        decoration: ShapeDecoration(
                          color: Color(0xFF61656D),
                          shape: OvalBorder(),
                        ),
                      ),
                      const SizedBox(width: 2),
                      Container(
                        width: 8,
                        height: 8,
                        decoration: ShapeDecoration(
                          color: Color(0xFF61656D),
                          shape: OvalBorder(),
                        ),
                      ),
                      const SizedBox(width: 2),
                      Container(
                        width: 8,
                        height: 8,
                        decoration: ShapeDecoration(
                          color: Color(0xFF61656D),
                          shape: OvalBorder(),
                        ),
                      ),
                      const SizedBox(width: 2),
                      Container(
                        width: 8,
                        height: 8,
                        decoration: ShapeDecoration(
                          color: Color(0xFF61656D),
                          shape: OvalBorder(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}